"""MariaDB backend namespace for snekql.

Import the whole MariaDB surface from here: dialect-neutral builders,
predicates, runtime, and type helpers (shared via ``snekql._common``), plus
MariaDB's write verbs, ``Model`` base, and column constructors (including the
JSON column and its path operators). There is no flat ``snekql.*`` surface; pick
a backend namespace and import everything from it.
"""

from __future__ import annotations

from snekql._common import (
    MISSING,
    Aggregate,
    Assignment,
    Attr,
    Col,
    Database,
    DatabaseClosedError,
    DatabaseCloseTimeoutError,
    DatabaseClosingError,
    DatabaseRuntimeError,
    DeleteQuery,
    ExecutionError,
    Fetched,
    FKAttr,
    FKCol,
    FrozenModelError,
    GenCol,
    Index,
    InsertManyQuery,
    InsertManyReturningQuery,
    InsertManyReturningTupleQuery,
    InsertManyReturningValueQuery,
    InsertQuery,
    InsertReturningQuery,
    InsertReturningTupleQuery,
    InsertReturningValueQuery,
    JoinModelQuery,
    JoinOn,
    MigrationError,
    MigrationLockTimeoutError,
    Missing,
    ModelDeclarationError,
    ModelError,
    ModelMeta,
    ModelValidationError,
    MultipleResultsError,
    NoResultError,
    OrderBy,
    Pending,
    PoolTimeoutError,
    Predicate,
    QueryCompilationError,
    QueryConstructionError,
    QueryError,
    Scalar,
    SchemaError,
    SchemaPolicy,
    SchemaVerificationError,
    SelectModelQuery,
    SelectTupleQuery,
    SelectValueQuery,
    SnekqlError,
    Table,
    Transaction,
    TransactionClosedError,
    UpdateQuery,
    exists,
    not_exists,
    scalar,
    select,
)

# Importing the query module registers the MariaDB query Dialect so a built
# MariaDB query can render its own SQL for inspection (see _query_dialect).
from snekql.mariadb import query as query
from snekql.mariadb.config import Config
from snekql.mariadb.model import Model
from snekql.mariadb.storage import (
    Blob,
    Boolean,
    CurrentTimestamp,
    DateTime,
    ForeignKey,
    Integer,
    Json,
    JsonAttr,
    Real,
    Text,
    Uuid,
)
from snekql.mariadb.verbs import delete, insert, update

__all__ = [
    "MISSING",
    "Aggregate",
    "Assignment",
    "Attr",
    "Blob",
    "Boolean",
    "Col",
    "Config",
    "CurrentTimestamp",
    "Database",
    "DatabaseCloseTimeoutError",
    "DatabaseClosedError",
    "DatabaseClosingError",
    "DatabaseRuntimeError",
    "DateTime",
    "DeleteQuery",
    "ExecutionError",
    "FKAttr",
    "FKCol",
    "Fetched",
    "ForeignKey",
    "FrozenModelError",
    "GenCol",
    "Index",
    "InsertManyQuery",
    "InsertManyReturningQuery",
    "InsertManyReturningTupleQuery",
    "InsertManyReturningValueQuery",
    "InsertQuery",
    "InsertReturningQuery",
    "InsertReturningTupleQuery",
    "InsertReturningValueQuery",
    "Integer",
    "JoinModelQuery",
    "JoinOn",
    "Json",
    "JsonAttr",
    "MigrationError",
    "MigrationLockTimeoutError",
    "Missing",
    "Model",
    "ModelDeclarationError",
    "ModelError",
    "ModelMeta",
    "ModelValidationError",
    "MultipleResultsError",
    "NoResultError",
    "OrderBy",
    "Pending",
    "PoolTimeoutError",
    "Predicate",
    "QueryCompilationError",
    "QueryConstructionError",
    "QueryError",
    "Real",
    "Scalar",
    "SchemaError",
    "SchemaPolicy",
    "SchemaVerificationError",
    "SelectModelQuery",
    "SelectTupleQuery",
    "SelectValueQuery",
    "SnekqlError",
    "Table",
    "Text",
    "Transaction",
    "TransactionClosedError",
    "UpdateQuery",
    "Uuid",
    "delete",
    "exists",
    "insert",
    "not_exists",
    "scalar",
    "select",
    "update",
]
