"""MariaDB backend namespace for snekql.

Import the whole MariaDB surface from here: dialect-neutral builders,
predicates, runtime, and type helpers (shared via ``snekql._common``), plus
MariaDB's write verbs, ``Model`` base, and column constructors (including the
JSON column and its path operators). There is no flat ``snekql.*`` surface; pick
a backend namespace and import everything from it.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal

from snekql._common import (
    PENDING_GENERATION,
    Aggregate,
    Assignment,
    Canonical,
    CanonicalDecimal,
    CheckConstraint,
    ChunkStream,
    ColumnRef,
    CommitOutcome,
    CompiledQuery,
    DatabaseClosedError,
    DatabaseCloseTimeoutError,
    DatabaseClosingError,
    DatabaseFailure,
    DatabaseOperationTimeoutError,
    DatabaseRuntimeError,
    DoNothing,
    DoUpdate,
    Duration,
    ExecutionError,
    ExplainResult,
    FailureCategory,
    ForeignKeyConstraint,
    FrozenModelError,
    Index,
    IsolationLevel,
    JoinOn,
    LexicalDatetimeWarning,
    LexicalDecimalWarning,
    LexicalDurationWarning,
    LiteralDefault,
    MigrationDeclarationError,
    MigrationError,
    MigrationHistoryError,
    MigrationLockError,
    MigrationLockTimeoutError,
    MigrationResult,
    MigrationStatus,
    ModelDeclarationError,
    ModelError,
    ModelValidationError,
    MultipleResultsError,
    NoResultError,
    Observer,
    OrderBy,
    OrderPreserving,
    Pending,
    PendingGeneration,
    PoolStats,
    PoolTimeoutError,
    Predicate,
    QueryCompilationError,
    QueryConstructionError,
    QueryError,
    RawResultShapeError,
    RawResultValidationError,
    ResultCardinalityError,
    Row,
    Scalar,
    SchemaDriftIssue,
    SchemaError,
    SchemaPolicy,
    SchemaVerificationError,
    SchemaVerificationFact,
    SchemaVerificationResult,
    SnekqlError,
    SnekqlWarning,
    TelemetryEvent,
    TransactionClosedError,
    TransactionMode,
    TransactionNotStartedError,
    TransactionReuseError,
    TransactionStateError,
    UtcDatetime,
    ZonedDatetime,
    ZonedDatetimeError,
    exists,
    not_exists,
    scalar,
)
from snekql._common import (
    Write as _RuntimeWrite,
)

# Importing the dialect module registers the MariaDB query Dialect so a built
# MariaDB query can render its own SQL for inspection (see _query_dialect).
from snekql.mariadb import _dialect_sql as _dialect_sql
from snekql.mariadb._raw import RawStatement, raw
from snekql.mariadb.config import Config, TLSConfig
from snekql.mariadb.functions import case, literal
from snekql.mariadb.model import Col, FKCol, GenCol, JsonCol, Model, complete
from snekql.mariadb.schema import scaffold_mariadb_ddl as scaffold
from snekql.mariadb.storage import (
    Blob,
    Boolean,
    CurrentTimestamp,
    DateTime,
    Decimal,
    ForeignKey,
    Integer,
    Json,
    LongText,
    Real,
    Text,
    Uuid,
)
from snekql.mariadb.verbs import (
    ClosedOptional,
    ClosedRead,
    OptionalRead,
    PendingInput,
    ReadQuery,
    alias,
    delete,
    insert,
    insert_many,
    ready,
    select,
    update,
)
from snekql.model import ReadType, is_complete
from snekql.query import _Write
from snekql.runtime import Database as _Database
from snekql.runtime import Transaction as _Transaction

if TYPE_CHECKING:
    Database = _Database[Literal["mariadb"]]
    Transaction = _Transaction[Literal["mariadb"]]
    type Write[ResultT] = _Write[Literal["mariadb"], ResultT]
else:
    Database = _Database
    Transaction = _Transaction
    Write = _RuntimeWrite

from snekql.mariadb.recursive import Cte, NamedOperand, recursive_cte

__all__ = [
    "PENDING_GENERATION",
    "Aggregate",
    "Assignment",
    "Blob",
    "Boolean",
    "Canonical",
    "CanonicalDecimal",
    "CheckConstraint",
    "ChunkStream",
    "ClosedOptional",
    "ClosedRead",
    "Col",
    "ColumnRef",
    "CommitOutcome",
    "CompiledQuery",
    "Config",
    "Cte",
    "CurrentTimestamp",
    "Database",
    "DatabaseCloseTimeoutError",
    "DatabaseClosedError",
    "DatabaseClosingError",
    "DatabaseFailure",
    "DatabaseOperationTimeoutError",
    "DatabaseRuntimeError",
    "DateTime",
    "Decimal",
    "DoNothing",
    "DoUpdate",
    "Duration",
    "ExecutionError",
    "ExplainResult",
    "FKCol",
    "FailureCategory",
    "ForeignKey",
    "ForeignKeyConstraint",
    "FrozenModelError",
    "GenCol",
    "Index",
    "Integer",
    "IsolationLevel",
    "JoinOn",
    "Json",
    "JsonCol",
    "LexicalDatetimeWarning",
    "LexicalDecimalWarning",
    "LexicalDurationWarning",
    "LiteralDefault",
    "LongText",
    "MigrationDeclarationError",
    "MigrationError",
    "MigrationHistoryError",
    "MigrationLockError",
    "MigrationLockTimeoutError",
    "MigrationResult",
    "MigrationStatus",
    "Model",
    "ModelDeclarationError",
    "ModelError",
    "ModelValidationError",
    "MultipleResultsError",
    "NamedOperand",
    "NoResultError",
    "Observer",
    "OptionalRead",
    "OrderBy",
    "OrderPreserving",
    "Pending",
    "PendingGeneration",
    "PendingInput",
    "PoolStats",
    "PoolTimeoutError",
    "Predicate",
    "QueryCompilationError",
    "QueryConstructionError",
    "QueryError",
    "RawResultShapeError",
    "RawResultValidationError",
    "RawStatement",
    "ReadQuery",
    "ReadType",
    "Real",
    "ResultCardinalityError",
    "Row",
    "Scalar",
    "SchemaDriftIssue",
    "SchemaError",
    "SchemaPolicy",
    "SchemaVerificationError",
    "SchemaVerificationFact",
    "SchemaVerificationResult",
    "SnekqlError",
    "SnekqlWarning",
    "TLSConfig",
    "TelemetryEvent",
    "Text",
    "Transaction",
    "TransactionClosedError",
    "TransactionMode",
    "TransactionNotStartedError",
    "TransactionReuseError",
    "TransactionStateError",
    "UtcDatetime",
    "Uuid",
    "Write",
    "ZonedDatetime",
    "ZonedDatetimeError",
    "alias",
    "case",
    "complete",
    "delete",
    "exists",
    "insert",
    "insert_many",
    "is_complete",
    "literal",
    "not_exists",
    "raw",
    "ready",
    "recursive_cte",
    "scaffold",
    "scalar",
    "select",
    "update",
]
