"""Property-based storage codec tests for SQLite.

These complement the example-based tests in ``test_storage_codecs.py``: instead
of pinning a handful of representative values, they assert the codec invariants
(``decode(encode(x)) == x`` inside each column's declared domain, and a domain
error outside it) across inputs generated by Hypothesis. They run purely against
the column descriptors' ``encode``/``decode`` surface -- no database -- so they
stay fast and deterministic.
"""

from __future__ import annotations

import math
import uuid
from datetime import UTC, datetime, timedelta, timezone
from typing import Any, cast

from hypothesis import settings
from hypothesis import strategies as st
from pydantic import Json
from snektest import (
    assert_eq,
    assert_isinstance,
    assert_raises,
    test_hypothesis,
)

from snekql.sqlite import (
    Blob,
    Fetched,
    Integer,
    Model,
    ModelValidationError,
    Pending,
    Real,
    Text,
)

BACKEND = "sqlite"

_INT64_MIN = -(2**63)
_INT64_MAX = 2**63 - 1


class Scalars[S = Pending](Model[S, "Scalars[Fetched]"]):
    """One column per SQLite storage class / logical type under test."""

    number: Scalars.Col[int] = Integer(nullable=False)
    rating: Scalars.Col[float] = Real(nullable=False)
    label: Scalars.Col[str] = Text(nullable=False)
    blob: Scalars.Col[bytes] = Blob(nullable=False)
    flag: Scalars.Col[bool] = Integer(nullable=False)
    when: Scalars.Col[datetime] = Text(nullable=False)
    # The pydantic ``Json`` marker -- not the dict value -- selects the JSON wire
    # codec over a plain TEXT column.
    data: Scalars.Col[Json[dict[str, Any]]] = Text(nullable=False)


# JSON payloads: arbitrarily nested, with only JSON-representable leaves. Text is
# restricted to UTF-8-encodable characters (no lone surrogates) so the wire codec
# never fails on un-encodable strings -- that is a separate, known limitation.
_json_text = st.text(st.characters(codec="utf-8"))
_json_leaves = (
    st.none()
    | st.booleans()
    | st.integers()
    | st.floats(allow_nan=False, allow_infinity=False)
    | _json_text
)
_json_values = st.recursive(
    _json_leaves,
    lambda children: (
        st.lists(children, max_size=5)
        | st.dictionaries(_json_text, children, max_size=5)
    ),
    max_leaves=15,
)
_json_objects = st.dictionaries(_json_text, _json_values, max_size=5)

# A datetime over TEXT canonicalizes to a UTC millisecond instant (issue #212),
# so any *aware* datetime -- UTC, whole-minute, or historical sub-minute offset --
# round-trips to that floored-millisecond UTC instant. Naive datetimes have no
# offset to reduce to an instant and are rejected at encode instead -- tested
# separately below rather than excluded silently.
_any_offsets = st.integers(min_value=-(24 * 3600 - 1), max_value=24 * 3600 - 1).map(
    lambda seconds: timezone(timedelta(seconds=seconds))
)
_aware_datetimes = st.datetimes(
    min_value=datetime(1900, 1, 1),  # noqa: DTZ001
    max_value=datetime(2200, 1, 1),  # noqa: DTZ001
    timezones=st.just(UTC) | _any_offsets,
)
_naive_datetimes = st.datetimes(
    min_value=datetime(1900, 1, 1),  # noqa: DTZ001
    max_value=datetime(2200, 1, 1),  # noqa: DTZ001
    timezones=st.none(),
)


def _floored_utc_instant(value: datetime) -> datetime:
    """The canonical stored form: UTC, floored to millisecond precision."""

    in_utc = value.astimezone(UTC)
    return in_utc.replace(microsecond=in_utc.microsecond // 1000 * 1000)


@settings(deadline=None)
@test_hypothesis(st.integers(min_value=_INT64_MIN, max_value=_INT64_MAX), mark="fast")
def integer_in_range_round_trips(value: int) -> None:
    """Every signed 64-bit integer encodes unchanged and decodes back."""

    encoded = Scalars.number.encode(value, backend=BACKEND)
    assert_eq(encoded, value)
    assert_eq(Scalars.number.decode(encoded, backend=BACKEND), value)


@settings(deadline=None)
@test_hypothesis(
    st.integers(min_value=_INT64_MAX + 1) | st.integers(max_value=_INT64_MIN - 1),
    mark="fast",
)
def integer_out_of_range_is_rejected(value: int) -> None:
    """Values past the signed 64-bit range fail at encode with a domain error."""

    with assert_raises(ModelValidationError):
        _ = Scalars.number.encode(value, backend=BACKEND)


@settings(deadline=None)
@test_hypothesis(st.floats(allow_nan=False, allow_infinity=False), mark="fast")
def finite_real_round_trips(value: float) -> None:
    """Finite floats round-trip exactly."""

    encoded = Scalars.rating.encode(value, backend=BACKEND)
    decoded = cast("float", Scalars.rating.decode(encoded, backend=BACKEND))
    # Use the bit pattern so that 0.0 / -0.0 and other signed values are
    # distinguished (``==`` treats +0.0 and -0.0 as equal).
    assert_eq(math.copysign(1.0, decoded), math.copysign(1.0, value))
    assert_eq(decoded, value)


@settings(deadline=None)
@test_hypothesis(st.sampled_from([math.nan, math.inf, -math.inf]), mark="fast")
def non_finite_real_is_rejected(value: float) -> None:
    """nan / inf / -inf are rejected with a domain error before persistence."""

    with assert_raises(ModelValidationError):
        _ = Scalars.rating.encode(value, backend=BACKEND)


@settings(deadline=None)
@test_hypothesis(st.text(), mark="fast")
def text_round_trips(value: str) -> None:
    """SQLite TEXT imposes no length limit; any string round-trips unchanged."""

    encoded = Scalars.label.encode(value, backend=BACKEND)
    assert_eq(Scalars.label.decode(encoded, backend=BACKEND), value)


@settings(deadline=None)
@test_hypothesis(st.binary(), mark="fast")
def blob_round_trips(value: bytes) -> None:
    """Any byte string round-trips unchanged through a BLOB column."""

    encoded = Scalars.blob.encode(value, backend=BACKEND)
    assert_eq(Scalars.blob.decode(encoded, backend=BACKEND), value)


@settings(deadline=None)
@test_hypothesis(st.booleans(), mark="fast")
def boolean_round_trips_through_integer(value: bool) -> None:  # noqa: FBT001
    """``Col[bool]`` over INTEGER stores 1/0 and decodes back to a real bool."""

    encoded = Scalars.flag.encode(value, backend=BACKEND)
    assert_eq(encoded, int(value))
    decoded = Scalars.flag.decode(int(value), backend=BACKEND)
    assert_isinstance(decoded, bool)
    assert_eq(decoded, value)


@settings(deadline=None)
@test_hypothesis(st.integers().filter(lambda n: n not in (0, 1)), mark="fast")
def boolean_decode_rejects_non_binary_integers(value: int) -> None:
    """A boolean column decodes only 0/1; any other stored integer is rejected."""

    with assert_raises(ModelValidationError):
        _ = Scalars.flag.decode(value, backend=BACKEND)


@settings(deadline=None)
@test_hypothesis(_aware_datetimes, mark="fast")
def datetime_round_trips_at_millisecond_utc(value: datetime) -> None:
    """An aware datetime stored as ISO text canonicalizes to a UTC millisecond
    instant (issue #212): decode recovers that floored-millisecond UTC value
    regardless of the input's original offset or sub-millisecond precision."""

    encoded = Scalars.when.encode(value, backend=BACKEND)
    assert_eq(
        Scalars.when.decode(encoded, backend=BACKEND), _floored_utc_instant(value)
    )


@settings(deadline=None)
@test_hypothesis(_naive_datetimes, mark="fast")
def naive_datetime_is_rejected(value: datetime) -> None:
    """A naive datetime has no offset to reduce it to a single instant, so it
    cannot be canonicalized for comparison and is rejected at encode with a
    domain error (matching the MariaDB native ``DateTime`` contract)."""

    with assert_raises(ModelValidationError):
        _ = Scalars.when.encode(value, backend=BACKEND)


@settings(deadline=None)
@test_hypothesis(st.uuids(), mark="fast")
def uuid_round_trips_as_text(value: uuid.UUID) -> None:
    """A UUID logical type round-trips through its string form on the wire."""

    class Account[S = Pending](Model[S, "Account[Fetched]"]):
        """Model binding a UUID logical type over TEXT."""

        account_id: Account.Col[uuid.UUID] = Text(nullable=False)

    encoded = Account.account_id.encode(value, backend=BACKEND)
    assert_eq(encoded, str(value))
    assert_eq(Account.account_id.decode(encoded, backend=BACKEND), value)


@settings(deadline=None)
@test_hypothesis(_json_objects, mark="fast")
def json_round_trips_arbitrary_payloads(value: dict[str, Any]) -> None:
    """The JSON wire codec round-trips arbitrarily nested objects/arrays."""

    encoded = Scalars.data.encode(value, backend=BACKEND)
    assert_isinstance(encoded, str)
    assert_eq(Scalars.data.decode(encoded, backend=BACKEND), value)
