"""Property-based tests for the backend-neutral schema DDL compiler.

The example tests pin exact DDL for representative models. These assert the
structural invariants the shared compiler in ``snekql._schema_compile`` must hold
for *any* plan, across identifiers generated by Hypothesis -- including names
that contain a dialect's own delimiter, the inputs most able to break quoting.

Both real quoters (SQLite double-quote, MariaDB backtick) are exercised, since
the shared compiler is parameterized by the dialect's ``quote_identifier`` and
must remain correct under either. The central invariant is that every identifier
reaches the DDL only in its quoted form, so a crafted table/column/constraint
name cannot escape into the surrounding statement.
"""

from __future__ import annotations

from typing import Any, cast

from hypothesis import strategies as st
from snektest import assert_true, test_hypothesis

from snekql._schema_compile import (
    compile_create_index_sql,
    compile_create_table_sql,
    compile_foreign_key_constraint,
)
from snekql._schema_dialect import SchemaDialect
from snekql._schema_plan import PlannedColumn, PlannedForeignKey, PlannedModel
from snekql._schema_shape import ColumnShape, IndexShape
from snekql.indexes import NormalizedIndex
from snekql.mariadb.identifiers import quote_identifier as quote_mariadb
from snekql.sqlite import Integer
from snekql.sqlite.identifiers import quote_identifier as quote_sqlite

# Identifier names: a plain alphabet plus a delimiter-rich one, so the generated
# names regularly contain the very characters quoting must escape.
_names = st.text(min_size=1, max_size=10) | st.text(
    st.sampled_from(['"', "`", "a", "_", "x"]), min_size=1, max_size=8
)
_actions = st.none() | st.sampled_from(("CASCADE", "RESTRICT", "SET NULL", "NO ACTION"))
_action_pairs = st.tuples(_actions, _actions)
_QUOTERS = (quote_sqlite, quote_mariadb)
_TABLE_SUFFIX = "MYSUFFIX"

_DUMMY_SHAPE = ColumnShape(
    name="",
    storage_type="INTEGER",
    nullable=True,
    primary_key=False,
    auto_increment=False,
    server_default=None,
    collation=None,
)


def _dialect(quote: Any) -> SchemaDialect:
    """A schema dialect whose column definitions surface the quoted column name.

    Only ``quote_identifier`` carries real per-backend behaviour here; the column
    definition is a stand-in that echoes the quoted name so the table compiler's
    own quoting (table name, composite PK, FK constraints) is what gets asserted.
    """

    return SchemaDialect(
        quote_identifier=quote,
        compile_column_definition=lambda column: f"{quote(column.name)} INTEGER",
        expected_column_shape=lambda _column: _DUMMY_SHAPE,
        expected_index_shape=lambda index: IndexShape(
            column_names=index.column_names,
            name=index.name,
            unique=index.unique,
        ),
        normalize_foreign_key_action=lambda action: action or "NO ACTION",
        table_suffix=_TABLE_SUFFIX,
        verifies_foreign_keys=True,
    )


@test_hypothesis(
    st.sampled_from(_QUOTERS),
    _names,
    _names,
    st.lists(_names, min_size=1, max_size=4),
    st.booleans(),
    mark="fast",
)
def create_index_quotes_every_identifier(
    quote: Any,
    table: str,
    index_name: str,
    columns: list[str],
    unique: bool,  # noqa: FBT001
) -> None:
    """CREATE INDEX wraps the index, table, and every column name in quotes."""

    index = NormalizedIndex(column_names=tuple(columns), name=index_name, unique=unique)
    sql = compile_create_index_sql(table, index, _dialect(quote))

    # The UNIQUE keyword sits before any quoted name, so the fixed prefix is an
    # unambiguous signal even when a name happens to contain the word "UNIQUE".
    prefix = "CREATE UNIQUE INDEX " if unique else "CREATE INDEX "
    assert_true(sql.startswith(prefix))
    assert_true(f"{quote(index_name)} ON {quote(table)} (" in sql)
    for column in columns:
        assert_true(quote(column) in sql)


@test_hypothesis(
    st.sampled_from(_QUOTERS),
    _names,
    _names,
    _names,
    _action_pairs,
    mark="fast",
)
def foreign_key_constraint_quotes_names_and_appends_actions(
    quote: Any,
    column: str,
    target_table: str,
    target_column: str,
    actions: tuple[str | None, str | None],
) -> None:
    """A FK constraint quotes all three names and appends only the set actions,
    ON DELETE before ON UPDATE."""

    on_delete, on_update = actions
    foreign_key = PlannedForeignKey(
        column_name=column,
        target_table=target_table,
        target_column=target_column,
        on_delete=on_delete,
        on_update=on_update,
    )
    constraint = compile_foreign_key_constraint(foreign_key, _dialect(quote))

    assert_true(constraint.startswith(f"FOREIGN KEY ({quote(column)}) "))
    assert_true(
        f"REFERENCES {quote(target_table)} ({quote(target_column)})" in constraint
    )
    if on_delete is not None:
        assert_true(f" ON DELETE {on_delete}" in constraint)
    if on_update is not None:
        assert_true(f" ON UPDATE {on_update}" in constraint)
    if on_delete is not None and on_update is not None:
        assert_true(constraint.index(" ON DELETE ") < constraint.index(" ON UPDATE "))


@st.composite
def _planned_models(draw: st.DrawFn) -> PlannedModel:
    """Compose a plan: a named table with unique columns and some FK constraints."""

    column_names = draw(
        st.lists(_names, min_size=1, max_size=4, unique=True),
    )
    columns = tuple(
        PlannedColumn(column=Integer(), name=name, composite_pk=draw(st.booleans()))
        for name in column_names
    )
    foreign_keys = tuple(
        PlannedForeignKey(
            column_name=draw(_names),
            target_table=draw(_names),
            target_column=draw(_names),
            on_delete=draw(_actions),
            on_update=draw(_actions),
        )
        for _ in range(draw(st.integers(min_value=0, max_value=2)))
    )
    return PlannedModel(
        columns=columns,
        foreign_keys=foreign_keys,
        indexes=(),
        model=cast("Any", object),
        table_name=draw(_names),
    )


@test_hypothesis(st.sampled_from(_QUOTERS), _planned_models(), mark="fast")
def create_table_quotes_table_and_columns_and_appends_constraints(
    quote: Any, planned: PlannedModel
) -> None:
    """CREATE TABLE quotes the table name, surfaces every column, appends FK
    constraints and a composite PRIMARY KEY clause, and ends with the suffix."""

    dialect = _dialect(quote)
    sql = compile_create_table_sql(planned, dialect)

    assert_true(sql.startswith(f"CREATE TABLE {quote(planned.table_name)} ("))
    assert_true(sql.endswith(f") {_TABLE_SUFFIX}"))
    for column in planned.columns:
        assert_true(quote(column.name) in sql)
    if any(column.composite_pk for column in planned.columns):
        assert_true("PRIMARY KEY (" in sql)
    for foreign_key in planned.foreign_keys:
        assert_true(compile_foreign_key_constraint(foreign_key, dialect) in sql)
