CREATE TABLE products (
	id BIGINT NOT NULL AUTO_INCREMENT, 
	price NUMERIC(10, 2) NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE cent_products (
	id BIGINT NOT NULL AUTO_INCREMENT, 
	price_cents BIGINT NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE orders (
	id BIGINT NOT NULL AUTO_INCREMENT, 
	quantity BIGINT NOT NULL, 
	status VARCHAR(255) NOT NULL, 
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), 
	PRIMARY KEY (id)
);
