CREATE TABLE `products` (`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, `price` DECIMAL(10,2) NOT NULL) ENGINE=InnoDB;

CREATE TABLE `cent_products` (`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, `price_cents` BIGINT NOT NULL) ENGINE=InnoDB;

CREATE TABLE `orders` (`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, `quantity` BIGINT NOT NULL, `status` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL, `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB;
