CREATE TABLE products (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	price NUMERIC(10, 2) NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE cent_products (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	price_cents INTEGER NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE orders (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	quantity INTEGER NOT NULL, 
	status VARCHAR(255) NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id)
);
