CREATE TABLE products (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	price TEXT NOT NULL
)
 STRICT;

CREATE TABLE cent_products (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	price_cents INTEGER NOT NULL
)
 STRICT;

CREATE TABLE orders (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	quantity INTEGER NOT NULL, 
	status TEXT NOT NULL, 
	created_at TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL
)
 STRICT;
