CREATE TABLE "products" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "price" TEXT NOT NULL) STRICT;

CREATE TABLE "cent_products" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "price_cents" INTEGER NOT NULL) STRICT;

CREATE TABLE "orders" ("id" INTEGER PRIMARY KEY AUTOINCREMENT, "quantity" INTEGER NOT NULL, "status" TEXT NOT NULL, "created_at" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))) STRICT;
