"""Public API surface for snekql."""

from __future__ import annotations

from snekql import sqlite as sqlite
from snekql.errors import (
    DatabaseClosedError,
    DatabaseCloseTimeoutError,
    DatabaseClosingError,
    DatabaseRuntimeError,
    ExecutionError,
    FrozenModelError,
    ModelDeclarationError,
    ModelError,
    ModelValidationError,
    PoolTimeoutError,
    QueryCompilationError,
    QueryConstructionError,
    QueryError,
    SchemaError,
    SchemaVerificationError,
    SnekqlError,
    TransactionClosedError,
)
from snekql.expressions import Assignment, OrderBy, Predicate
from snekql.model import (
    Col,
    Fetched,
    GenCol,
    Model,
    ModelMeta,
    Pending,
    Table,
)
from snekql.query import (
    DeleteQuery,
    InsertQuery,
    SelectModelQuery,
    SelectTupleQuery,
    SelectValueQuery,
    UpdateQuery,
    delete,
    insert,
    select,
    update,
)
from snekql.runtime import Database, Transaction
from snekql.storage import (
    MISSING,
    Attr,
    Blob,
    Boolean,
    CurrentTimestamp,
    DateTime,
    Integer,
    Json,
    Missing,
    Real,
    SchemaPolicy,
    Text,
)

__all__ = [
    "MISSING",
    "Assignment",
    "Attr",
    "Blob",
    "Boolean",
    "Col",
    "CurrentTimestamp",
    "Database",
    "DatabaseCloseTimeoutError",
    "DatabaseClosedError",
    "DatabaseClosingError",
    "DatabaseRuntimeError",
    "DateTime",
    "DeleteQuery",
    "ExecutionError",
    "Fetched",
    "FrozenModelError",
    "GenCol",
    "InsertQuery",
    "Integer",
    "Json",
    "Missing",
    "Model",
    "ModelDeclarationError",
    "ModelError",
    "ModelMeta",
    "ModelValidationError",
    "OrderBy",
    "Pending",
    "PoolTimeoutError",
    "Predicate",
    "QueryCompilationError",
    "QueryConstructionError",
    "QueryError",
    "Real",
    "SchemaError",
    "SchemaPolicy",
    "SchemaVerificationError",
    "SelectModelQuery",
    "SelectTupleQuery",
    "SelectValueQuery",
    "SnekqlError",
    "Table",
    "Text",
    "Transaction",
    "TransactionClosedError",
    "UpdateQuery",
    "delete",
    "insert",
    "select",
    "sqlite",
    "update",
]
