"""SQLite backend namespace for snekql.

Import the whole SQLite surface from here: dialect-neutral builders,
predicates, runtime, and type helpers (shared via ``snekql._common``), plus
SQLite's write verbs, ``Model`` base, and column constructors. There is no flat
``snekql.*`` surface; pick a backend namespace and import everything from it.
"""

from __future__ import annotations

from snekql._common import (
    PENDING_GENERATION,
    Aggregate,
    Assignment,
    Attr,
    Col,
    Database,
    DatabaseClosedError,
    DatabaseCloseTimeoutError,
    DatabaseClosingError,
    DatabaseRuntimeError,
    DeleteQuery,
    DeleteReturningQuery,
    DeleteReturningTupleQuery,
    DeleteReturningValueQuery,
    ExecutionError,
    Fetched,
    FKAttr,
    FKCol,
    FrozenModelError,
    GenCol,
    Index,
    InsertManyQuery,
    InsertManyReturningQuery,
    InsertManyReturningTupleQuery,
    InsertManyReturningValueQuery,
    InsertQuery,
    InsertReturningQuery,
    InsertReturningTupleQuery,
    InsertReturningValueQuery,
    JoinModelQuery,
    JoinOn,
    MigrationError,
    MigrationLockTimeoutError,
    ModelDeclarationError,
    ModelError,
    ModelMeta,
    ModelValidationError,
    MultipleResultsError,
    NoResultError,
    OrderBy,
    Pending,
    PendingGeneration,
    PoolTimeoutError,
    Predicate,
    QueryCompilationError,
    QueryConstructionError,
    QueryError,
    Scalar,
    SchemaError,
    SchemaPolicy,
    SchemaVerificationError,
    SelectModelQuery,
    SelectTupleQuery,
    SelectValueQuery,
    SnekqlError,
    Table,
    Transaction,
    TransactionClosedError,
    UpdateQuery,
    UpdateReturningQuery,
    UpdateReturningTupleQuery,
    UpdateReturningValueQuery,
    exists,
    not_exists,
    scalar,
    select,
)
from snekql.model import Model

# Importing the query module registers the SQLite query Dialect so a built
# SQLite query can render its own SQL for inspection (see _query_dialect).
from snekql.sqlite import query as query
from snekql.sqlite._schema_ddl import scaffold_sqlite_ddl as scaffold
from snekql.sqlite.config import Config
from snekql.sqlite.verbs import delete, insert, update
from snekql.storage import (
    Blob,
    CurrentTimestamp,
    ForeignKey,
    Integer,
    Real,
    Text,
)

__all__ = [
    "PENDING_GENERATION",
    "Aggregate",
    "Assignment",
    "Attr",
    "Blob",
    "Col",
    "Config",
    "CurrentTimestamp",
    "Database",
    "DatabaseCloseTimeoutError",
    "DatabaseClosedError",
    "DatabaseClosingError",
    "DatabaseRuntimeError",
    "DeleteQuery",
    "DeleteReturningQuery",
    "DeleteReturningTupleQuery",
    "DeleteReturningValueQuery",
    "ExecutionError",
    "FKAttr",
    "FKCol",
    "Fetched",
    "ForeignKey",
    "FrozenModelError",
    "GenCol",
    "Index",
    "InsertManyQuery",
    "InsertManyReturningQuery",
    "InsertManyReturningTupleQuery",
    "InsertManyReturningValueQuery",
    "InsertQuery",
    "InsertReturningQuery",
    "InsertReturningTupleQuery",
    "InsertReturningValueQuery",
    "Integer",
    "JoinModelQuery",
    "JoinOn",
    "MigrationError",
    "MigrationLockTimeoutError",
    "Model",
    "ModelDeclarationError",
    "ModelError",
    "ModelMeta",
    "ModelValidationError",
    "MultipleResultsError",
    "NoResultError",
    "OrderBy",
    "Pending",
    "PendingGeneration",
    "PoolTimeoutError",
    "Predicate",
    "QueryCompilationError",
    "QueryConstructionError",
    "QueryError",
    "Real",
    "Scalar",
    "SchemaError",
    "SchemaPolicy",
    "SchemaVerificationError",
    "SelectModelQuery",
    "SelectTupleQuery",
    "SelectValueQuery",
    "SnekqlError",
    "Table",
    "Text",
    "Transaction",
    "TransactionClosedError",
    "UpdateQuery",
    "UpdateReturningQuery",
    "UpdateReturningTupleQuery",
    "UpdateReturningValueQuery",
    "delete",
    "exists",
    "insert",
    "not_exists",
    "scaffold",
    "scalar",
    "select",
    "update",
]
