"""SQLite backend namespace for snekql.

Import the whole SQLite surface from here: dialect-neutral builders,
predicates, runtime, and type helpers (shared via ``snekql._common``), plus
SQLite's write verbs, ``Model`` base, and column constructors. There is no flat
``snekql.*`` surface; pick a backend namespace and import everything from it.
"""

from __future__ import annotations

from snekql._common import (
    PENDING_GENERATION,
    Aggregate,
    Assignment,
    Canonical,
    CanonicalDecimal,
    ChunkStream,
    Col,
    ColumnRef,
    Database,
    DatabaseClosedError,
    DatabaseCloseTimeoutError,
    DatabaseClosingError,
    DatabaseRuntimeError,
    DoNothing,
    DoUpdate,
    Duration,
    ExecutionError,
    Fetched,
    FKCol,
    FrozenModelError,
    GenCol,
    Index,
    JoinOn,
    LexicalDatetimeWarning,
    LexicalDecimalWarning,
    LexicalDurationWarning,
    MigrationError,
    MigrationLockTimeoutError,
    ModelDeclarationError,
    ModelError,
    ModelValidationError,
    MultipleResultsError,
    NoResultError,
    OrderBy,
    OrderPreserving,
    Pending,
    PendingGeneration,
    PoolTimeoutError,
    Predicate,
    QueryCompilationError,
    QueryConstructionError,
    QueryError,
    Scalar,
    SchemaError,
    SchemaPolicy,
    SchemaVerificationError,
    Select,
    SnekqlError,
    SnekqlWarning,
    Transaction,
    TransactionClosedError,
    TransactionMode,
    TransactionNotStartedError,
    TransactionReuseError,
    TransactionStateError,
    UtcDatetime,
    Write,
    exists,
    not_exists,
    scalar,
    select,
)
from snekql.model import Model

# Importing the dialect module registers the SQLite query Dialect so a built
# SQLite query can render its own SQL for inspection (see _query_dialect).
from snekql.sqlite import _dialect_sql as _dialect_sql
from snekql.sqlite._schema_ddl import scaffold_sqlite_ddl as scaffold
from snekql.sqlite.config import Config
from snekql.sqlite.verbs import delete, insert, update
from snekql.storage import (
    Blob,
    CurrentTimestamp,
    ForeignKey,
    Integer,
    Real,
    Text,
)

__all__ = [
    "PENDING_GENERATION",
    "Aggregate",
    "Assignment",
    "Blob",
    "Canonical",
    "CanonicalDecimal",
    "ChunkStream",
    "Col",
    "ColumnRef",
    "Config",
    "CurrentTimestamp",
    "Database",
    "DatabaseCloseTimeoutError",
    "DatabaseClosedError",
    "DatabaseClosingError",
    "DatabaseRuntimeError",
    "DoNothing",
    "DoUpdate",
    "Duration",
    "ExecutionError",
    "FKCol",
    "Fetched",
    "ForeignKey",
    "FrozenModelError",
    "GenCol",
    "Index",
    "Integer",
    "JoinOn",
    "LexicalDatetimeWarning",
    "LexicalDecimalWarning",
    "LexicalDurationWarning",
    "MigrationError",
    "MigrationLockTimeoutError",
    "Model",
    "ModelDeclarationError",
    "ModelError",
    "ModelValidationError",
    "MultipleResultsError",
    "NoResultError",
    "OrderBy",
    "OrderPreserving",
    "Pending",
    "PendingGeneration",
    "PoolTimeoutError",
    "Predicate",
    "QueryCompilationError",
    "QueryConstructionError",
    "QueryError",
    "Real",
    "Scalar",
    "SchemaError",
    "SchemaPolicy",
    "SchemaVerificationError",
    "Select",
    "SnekqlError",
    "SnekqlWarning",
    "Text",
    "Transaction",
    "TransactionClosedError",
    "TransactionMode",
    "TransactionNotStartedError",
    "TransactionReuseError",
    "TransactionStateError",
    "UtcDatetime",
    "Write",
    "delete",
    "exists",
    "insert",
    "not_exists",
    "scaffold",
    "scalar",
    "select",
    "update",
]
