CREATE TABLE orders (
	id BIGINT NOT NULL AUTO_INCREMENT, 
	price_cents BIGINT NOT NULL, 
	quantity BIGINT NOT NULL, 
	status VARCHAR(255) COLLATE utf8mb4_bin NOT NULL DEFAULT 'pending', 
	created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), 
	PRIMARY KEY (id), 
	CONSTRAINT ck_price_cents CHECK (price_cents BETWEEN 0 AND 9999999999), 
	CONSTRAINT ck_quantity CHECK (quantity BETWEEN 1 AND 2147483647)
);
