"""Throwaway schema with invariant field identities and precise values."""

from collections.abc import Callable
from typing import Protocol, Self

class Expr[T](Protocol):
    def __value_type__(self) -> T: ...

class Slot[KeyT, T]:
    def __key__(self, key: KeyT) -> KeyT: ...
    def __value_type__(self) -> T: ...

class Shape[SchemaT, LayoutT](Protocol):
    def schema(self, schema: SchemaT) -> SchemaT: ...
    def layout(self) -> LayoutT: ...

class EventSchema: ...
class IdKey: ...
class TitleKey: ...

class Fields[IdT: int | None, TitleT: str | None]:
    def __init__(self, *, event_id: Expr[IdT], title: Expr[TitleT]) -> None: ...
    @property
    def event_id(self) -> Slot[IdKey, IdT]: ...
    @property
    def title(self) -> Slot[TitleKey, TitleT]: ...
    def schema(self, schema: EventSchema) -> EventSchema: ...
    def layout(self) -> Self: ...

class Query[SchemaT, LayoutT]:
    def __schema__(self, schema: SchemaT) -> SchemaT: ...
    def union_all[OtherT](
        self, other: Query[SchemaT, OtherT]
    ) -> Combined[SchemaT, LayoutT, OtherT]: ...

class Combined[SchemaT, LeftT, RightT]:
    def __schema__(self, schema: SchemaT) -> SchemaT: ...
    def column[KeyT, T](
        self, choose: Callable[[LeftT | RightT], Slot[KeyT, T]]
    ) -> Slot[KeyT, T]: ...
    def union_all[OtherT](
        self, other: Query[SchemaT, OtherT]
    ) -> Combined[SchemaT, LeftT | RightT, OtherT]: ...

def project[SchemaT, LayoutT](
    fields: Shape[SchemaT, LayoutT],
) -> Query[SchemaT, LayoutT]: ...
def integer() -> Expr[int]: ...
def optional_integer() -> Expr[int | None]: ...
def text() -> Expr[str]: ...
def optional_text() -> Expr[str | None]: ...
