"""Throwaway explicit-schema signatures, not production query support."""

from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol, Self

class Expr[T](Protocol):
    def __value_type__(self) -> T: ...

class Shape[SchemaT, LayoutT](Protocol):
    def schema(self, schema: SchemaT) -> SchemaT: ...
    def layout(self) -> LayoutT: ...

class EventSchema: ...
class DifferentSchema: ...

@dataclass(frozen=True)
class Fields[IdT: int | None, TitleT: str | None]:
    event_id: Expr[IdT]
    title: Expr[TitleT]
    def schema(self, schema: EventSchema) -> EventSchema: ...
    def layout(self) -> Self: ...

@dataclass(frozen=True)
class DifferentFields[IdT: int | None]:
    event_id: Expr[IdT]
    def schema(self, schema: DifferentSchema) -> DifferentSchema: ...
    def layout(self) -> Self: ...

class Query[SchemaT, LayoutT]:
    def __schema__(self, schema: SchemaT) -> SchemaT: ...
    def union_all[OtherT](
        self, other: Query[SchemaT, OtherT]
    ) -> Combined[SchemaT, LayoutT, OtherT]: ...

class Combined[SchemaT, LeftT, RightT]:
    def __schema__(self, schema: SchemaT) -> SchemaT: ...
    def column[T](self, choose: Callable[[LeftT | RightT], Expr[T]]) -> Expr[T]: ...
    def union_all[OtherT](
        self, other: Query[SchemaT, OtherT]
    ) -> Combined[SchemaT, LeftT | RightT, OtherT]: ...

def project[SchemaT, LayoutT](
    fields: Shape[SchemaT, LayoutT],
) -> Query[SchemaT, LayoutT]: ...
def integer() -> Expr[int]: ...
def optional_integer() -> Expr[int | None]: ...
def text() -> Expr[str]: ...
def optional_text() -> Expr[str | None]: ...
