"""Throwaway per-result query signatures; handwritten, not generated."""

from dataclasses import dataclass
from typing import Protocol, overload

class Expr[T](Protocol):
    def __value_type__(self) -> T: ...

class SQLite: ...
class MariaDB: ...
class IdKey: ...
class TitleKey: ...

@dataclass(frozen=True)
class Columns[IdT, TitleT]:
    event_id: Expr[IdT]
    title: Expr[TitleT]

class Events[FamilyT, IdT: int | None, TitleT: str | None]:
    def __family__(self, family: FamilyT) -> FamilyT: ...
    @property
    def columns(self) -> Columns[IdT, TitleT]: ...
    @overload
    def column(self, key: IdKey) -> Expr[IdT]: ...
    @overload
    def column(self, key: TitleKey) -> Expr[TitleT]: ...
    def union_all[OtherIdT: int | None, OtherTitleT: str | None](
        self, other: Events[FamilyT, OtherIdT, OtherTitleT]
    ) -> Events[FamilyT, IdT | OtherIdT, TitleT | OtherTitleT]: ...
    def union[OtherIdT: int | None, OtherTitleT: str | None](
        self, other: Events[FamilyT, OtherIdT, OtherTitleT]
    ) -> Events[FamilyT, IdT | OtherIdT, TitleT | OtherTitleT]: ...

class OtherResult[FamilyT, IdT: int | None]:
    def __family__(self, family: FamilyT) -> FamilyT: ...

def project[FamilyT, IdT: int | None, TitleT: str | None](
    backend: type[FamilyT], *, event_id: Expr[IdT], title: Expr[TitleT]
) -> Events[FamilyT, IdT, TitleT]: ...
def other_result[FamilyT, IdT: int | None](
    backend: type[FamilyT], *, event_id: Expr[IdT]
) -> OtherResult[FamilyT, IdT]: ...
def integer() -> Expr[int]: ...
def optional_integer() -> Expr[int | None]: ...
def text() -> Expr[str]: ...
def optional_text() -> Expr[str | None]: ...

ID: IdKey
TITLE: TitleKey
