"""Throwaway variadic shape capture without elementwise type mapping."""

class Query[*Values]:
    def union_all(self, other: Query[*Values]) -> Query[*Values]: ...

def required() -> Query[int, str]: ...
def optional() -> Query[int | None, str]: ...
